### ISSUE TITLE
biography schema: odd attributes on P tag

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#100]
When I insert a p tag within a short prose tag I seem to be asked for required resp and url attributes:

![image](https://cloud.githubusercontent.com/assets/545952/7356395/d35d2842-ecf5-11e4-8f5d-e46c0d12e175.png)

**Comment by SusanBrown** [comment]
Mihaela thinks this may be a CWRC-Writer problem

**Comment by ilovan** [comment]
Fixed in current CWRC-Writer
