### ISSUE TITLE
CWRC entry: add "program" tag to education bucket

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Schema#102]
as per Playwrights request, to cover other types of education that don't culminate in a degree (e.g. workshops, summer schools, certificates, etc.)

**Comment by brundin** [comment]
Just to clarify, is the request to add the value "PROGRAM" to the attribute MODE in the element EDUCATION?  I.e., in addition to the values of DOMESTIC, INSTITUTIONAL, and SELF-TAUGHT in the MODE attribute, you would like the value PROGRAM added to this list?

**Comment by ilovan** [comment]
No - it's a new element mirroring the properties and locations of DEGREE http://cwrc.ca/schemas/documentation/CWRC_entry/index.html#DEGREE

**Comment by brundin** [comment]
Ah, I see -- thanks for clarifying.

**Comment by brundin** [comment]
Created a new element PROGRAM, that has the same child elements and ref locations as the element DEGREE.
