### ISSUE TITLE
Orlando schemas: remove attribute "PROPOSEDALTERNATIVENAME"

### ISSUE THREAD

**Issue by jefferya** [cwrc/CWRC-Schema#113]
Please remove the attribute "PROPOSEDALTERNATIVENAME" from the element "TGENRE" in the Orlando schemas. This attribute has been removed from existing Orlando documents to prevent confusion.

@ilovan  Should this be done in the CWRC schema also?

**Comment by brundin** [comment]
Will do for all the Orlando schemas.  I would assume the CWRC entry schema
as well.

On Mon, Sep 28, 2015 at 10:35 AM, Jeffery Antoniuk <notifications@github.com

**Comment by brundin** [comment]
Removed attribute PROPOSEDALTERNATIVENAME from the element TGENRE in all affected schemas.  Generated new schema documentation.
