### ISSUE TITLE
rename Orlando schemas once migration complete

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#116]
Once the migration of the schemas is complete and we no longer need the old versions that deal with entity references, rename the numbered Orlando schemas so that they are no longer numbered.

**Comment by jefferya** [comment]
Also, change any content created using the numbered schemas.

**Comment by brundin** [comment]
Do you mean after the migration of Orlando resources is complete, and we no
longer need the Orlando legacy date format to be defined in the Orlando
RELAX NG schemas, then rename the numbered Orlando schemas so that they are
no longer numbered?

**Comment by brundin** [comment]
Right -- after CWRC-Writer has been changed so that it no longer writes the
RDF annotations to the "rdf:RDF" bucket off of the root element of a
document, then remove the "any_content" and "any_node" XML blocks in all of
the schemas (Orlando, TEI, and CWRC entry).

**Comment by jefferya** [comment]
Change any processing instruction in the XML content and any other
references to the numbered schemas in the object (e.g. schema object
pointers).

**Comment by brundin** [comment]
I see -- so change Orlando legacy date formats to ISO 8601 date formats,
and also change any processing instruction "xml-model href" pointer
references to a "_v2" schema to the non-numbered Orlando schemas.

On Wed, Feb 10, 2016 at 10:52 AM, Jeffery Antoniuk <notifications@github.com
> wrote:

> Change any processing instruction in the XML content and any other
> references to the numbered schemas in the object (e.g. schema object
> pointers).
>

**Comment by ilovan** [comment]
no longer necessary, since we are moving towards an unified orlando_entry schema
