### ISSUE TITLE
MODS forms: if possible, in the MODS forms, relabel "Primary genre" to "Broad genre" and "Subgenre" to "Specific genre"

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#117]
This comes out of concern expressed in the Playwrights project in deciding on genres for their mini MODS forms, and I think it will be more generally confusing too, since "primary" means "main" on the face of it. 

@brundin I know we wouldn't want to change the element names in the schemas themselves, but if we can relabel that would be best, and if we can't then we should modify the help text that appears for those fields. If you feel we should retain the LOC nomenclature to some extent, a compromise would be "Broad genre (MODS primary genre)" and "Specific genre (MODS secondary genre)".

**Comment by jefferya** [comment]
How will these changes affect (1) the genre facets and (2) the EAP
specifications?

**Comment by SusanBrown** [comment]
I wouldn’t have thought they would affect the EAPs at all, but I am about (finally) to look at the EAP checklist so I’ve done that before the workweek starts, and I’ll bear that question in mind.

I would think you are best positioned to ask how it would affect genre facets, aren’t you? 

If we can just relabel the form without changing the element names, I would think that all we would need to do was relabel the facet.
If we change the elements names (which I would assume we can’t), then that might be more involved.

Let’s see what Michael says and then make the call. If we think it will be very time-consuming or complicate other things, we can leave it until after the May launch, but I think this will be confusing to other people so I think we should at least add better guidance in the gloss for the fields within the interface.

**Comment by brundin** [comment]
Hi,

That won't be a problem, we can relabel the MODS forms for the genre
elements.  For reference purposes, here is the link to the LOC page on the
MODS genre element: https://www.loc.gov/standards/mods/userguide/genre.html

We are using unique enumerated lists for are our three genre elements
("Format", "Primary Genre", and "Subgenre") on the MODS forms, and we are
distinguishing these three /mods/genre elements from one another by
qualifying them with a type attribute in the genre elements, with the three
different type attribute values of "format", "primaryGenre", and
"subgenre".  There is nothing sanctioned or codified by the Library of
Congress in the enumerated lists of text node values, the type attribute
values, nor in the label terminology we are using on the MODS forms.  We
also have a fourth genre element in the sense that we have MODS records
that have a genre element value, but there is no type attribute value
(these could be termed the "folksonomic" genre terms).

MRB

**Comment by SusanBrown** [comment]
That is excellent. And if I’m correct, then, this has minor implications for faceting and none at all for the EAPs. 

So we should devise and confirm vocabulary for the 4 elements. 

What about:
Format
Broad Genre
Specific Genre(s)
Additional Genre(s) (member-contributed terms)

Not elegant, but hopefully clear?

**Comment by brundin** [comment]
Clear, and scans well.

**Comment by brundin** [comment]
Have renamed the labels so "Primary Genre" is now "Broad Genre", and "Subgenre(s)" is now "Specific Genre(s)".  Also created a new MODS element of genre with no @type attribute qualifier, that is labeled "Additional Genre(s) (member-contributed terms)".  So including our genre/@type='format' element labeled "Format", we now have four genre elements labeled as indicated.
