### ISSUE TITLE
CWRC schema: RESP attribute required on the XREF tag

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Schema#119]
Does it need to be? It doesn't make a lot of sense to me. It also doesn't have a required TEI equivalent either.

**Comment by brundin** [comment]
I have just made the @RESP attribute optional in the XREF element in the cwrc_entry.rng schema.  It is still required in the Orlando RNG schemas, as I believe it is necessary for document check-in purposes in the Document Archive.
