### ISSUE TITLE
URI attribute on orgname tag in Orlando schemas

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#121]

**Comment by ilovan** [comment]
@SusanBrown , ORGNAME supports both REF and URI attributes with no clear distinction between the two in meaning (CWRC-Writer uses the REF attribute for linking named entities)  Any recollection on how we ended up with this duplication?

**Comment by SusanBrown** [comment]
No idea. Suggest removing URI for consistency.


On Apr 3, 2018, at 3:17 PM, Mihaela Ilovan <notifications@github.com<mailto:notifications@github.com>> wrote:


@SusanBrown<https://github.com/SusanBrown> , ORGNAME supports both REF and URI attributes with no clear distinction between the two in meaning (CWRC-Writer uses the REF attribute for linking named entities) Any recollection on how we ended up with this duplication?

**Comment by ilovan** [comment]
Single instance (empty URI) in the entrance for Katharine Bruce Glasier (added to the cleanup sheet). 
URI removed from the schema with https://github.com/cwrc/CWRC-Schema/commit/924694d4b2ad05736058a03c20db3eb9f1529f2d
