### ISSUE TITLE
TEI lite schema: change @cert attribute values

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Schema#125]
Current values:

- definite
- reasonably certain
- probable
- speculative

Requested values:

- high
- low
- medium
- unknown

**Comment by ilovan** [comment]
Jeff, I would like to do this in the TEI customization file and I know you were usually around to support Michael when he used to do this kind of schema change, so I will wait for your next sprint :)

https://github.com/cwrc/CWRC-Schema/issues/126 is very similar.

**Comment by SusanBrown** [comment]
Slight modification (I know you would almost certainly catch this):

Requested values:
- high
- medium
- low
- unknown

@joelacummings Are you fine to use these values for the ontology as well?

**Comment by ilovan** [comment]
I would like to point out before you make any decision about the values included in the ontology that TEI makes a semantic distinction between the cert attribute and the certainty element. 

See 

- http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-certainty.html

 and 

- http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.responsibility.html

**Comment by joelacummings** [comment]
@SusanBrown The values are ok with me. Thanks for the link @ilovan if both models are being used we will need to represent them both in the ontology.

**Comment by ilovan** [comment]
https://github.com/cwrc/CWRC-Schema/commit/7e988d0c9f7946c9f817f46c3959518f24f7b8cc
