### ISSUE TITLE
TEI schema: data.word

### ISSUE THREAD

**Issue by ajmacdonald** [cwrc/CWRC-Schema#128]
I'm curious about the pattern that's specified for [data.word](https://github.com/cwrc/CWRC-Schema/blob/master/schemas/cwrc_tei_lite.rng#L174-L178)
```
<define name="data.word">
  <data type="token">
    <param name="pattern">(\p{L}|\p{N}|\p{P}|\p{S})+</param>
  </data>
</define>
```
It will match strings like `p{L}p{N}`, which seems like a weird way to specify commodity, lang, mimeType, etc.
I think the regex might be incorrect or incomplete but I'm not sure.

**Comment by ilovan** [comment]
the definition is part of the TEI code: see https://www.tei-c.org/Vault/P5/1.0.0/doc/tei-p5-doc/en/html/ref-data.word.html 

syntax is xsd instead of rng but the regex is the same.

**Comment by ajmacdonald** [comment]
Ah ok. I see that the regex format is PCRE, which is why I didn't understand it.
