### ISSUE TITLE
chronevent tag missing?

### ISSUE THREAD

**Issue by susanirenebrown** [cwrc/CWRC-Schema#86]
The chronstruct tag seems to be present, but not the chronevent envelope that holds together a chronstruct with related paragraphs, if any

consider whether one of the named entities we want might be something like "eventname"

**Comment by brundin** [comment]
Created a new element CHRONEVENT, that has child elements of CHRONSTRUCT, SHORTPROSE, RESEARCHNOTES, BIBCITS, and KEYWORDCLASS; CHRONEVENT is available in the same elements that CHRONSTRUCT is available in.
