### ISSUE TITLE
wierdness with production element

### ISSUE THREAD

**Issue by ghost** [cwrc/CWRC-Schema#89]
This issue should really be called "wierdness with splitting elements"

Inside a P tag inside PRODUCTION, when I want to split the tag, I can't split the P tag directly, but only the PRODUCTION tag, which produces a new P tag as well, but unnecessarily multiplies the PRODUCTION tag. I can then move the text I want in the new P tag, along with the P tag, into the original PRODUCTION tag, and delete the PRODUCTION tag, and everything is just fine, but it is cumbersome: we should be able to split the P tag directly. Can you figure out why this is happening this way?

I just checked it with other tags and it's all the same: it wants to split the higher-level tag, not the one that the cursor is immediately within. This does not seem to be the case within TEXTUALFEATURES but it is also the case with RECEPTION.

this clip is from the Talia Pura doc:

![screen shot 2014-10-04 at 3 36 04 pm](https://cloud.githubusercontent.com/assets/879861/4516556/b58c76fe-4bfd-11e4-93f9-daa06355a82f.png)

Also had the same issue with trying to split genrename within a chronstruct:

![screen shot 2014-10-04 at 3 49 48 pm](https://cloud.githubusercontent.com/assets/879861/4516596/e014f584-4bff-11e4-8d12-572119413a7e.png)

**Comment by ilovan** [comment]
no longer an issue in the newest versions of Oxygen (tested in Oxygen 21.0)
