### ISSUE TITLE
Roles attributes: need more for drama (CWRC schema)

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#91]
In addition to the existing MARC roles we have in the picklist for this tag, we need the following two:
Acting Coach
Dramaturge
Leslie notes that more will probably arise as work on the playwrights project progresses. So we may want to put it off. Also if we can follow a standard vocabulary that would be great. Kathryn Harvey pointed me to one some time ago but I can't find it. I will need to consult her again.

**Comment by brundin** [comment]
- Added to the enumerated list of values for the ROLE element the following values: Agent, Assistant director, Clown, Filmmaker, Mask designer, Performance artist, Playwright, Projection designer, Special effects designer, Stage crew, and Understudy.  Note: Dancer, Puppeteer, and Translator were already in the enumerated list of values.
