### ISSUE TITLE
Add to tgenre attributes

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#93]
Theatre for young audiences
   Musical
   Podplay
   Collective Creation
   Physical Theatre
   Dance

**Comment by brundin** [comment]
- Added to the enumerated list of values for the attribute GENRENAME in the element TGENRE the following values: COLLECTIVECREATION, DANCE, MUSICAL, PHYSICALTHEATRE, PODPLAY, and THEATREFORYOUNGAUDIENCES.
