### ISSUE TITLE
CWRC TEI schema: make the event tag available outside a listEvent

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Schema#95]
description of listevent from TEI: (list of events) contains a list of descriptions, each of which provides information about an identifiable event

description of event from TEI: contains data relating to any kind of significant event associated with a person, place, or organization

**Comment by brundin** [comment]
The TEI schema is defined such that event needs to be a child of listEvent, listPerson, listOrg, listPlace, person, org, place, or event (event is recursive, i.e., event can have event as a child).  To change this would mean radically restructuring the TEI schema, and we want to be relatively TEI-conformant.  So, even if there is only one event, "best practices" for us would mean wrapping that single event in a listEvent container object.

**Comment by susanirenebrown** [comment]
I agree that remaining in conformant is the way to go.
