### ISSUE TITLE
fix omission of "male" in list of values for Sex tag

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#96]
Documentation current reads: 

Sex is an attribute applied to the CWRC
                            document as a whole, and specifies whether the individual who is the subject of the document is female, male, transgendered,
                            transgendered male-to-female, transgendered female-to-male, or undefined.

**Comment by brundin** [comment]
Confused.  In the list of values, here is the value for
male: <value>MALE</value>.

Let me know what I am missing here . . .

MRB

**Comment by SusanBrown** [comment]
It’s just that the word male is left out of the list of values in the documentation entry, not in the schema attribute values ;)

On March 3, 2015 at 12:39:11 AM, brundin (notifications@github.com) wrote:

Confused. In the list of values, here is the value for
male: <value>MALE</value>.

Let me know what I am missing here . . .

MRB

**Comment by ilovan** [comment]
From the documentation:

**Comment by susanirenebrown** [comment]
OK, sorry, my bad: the text was pushing off the screen so I’m sure “male” just wasn’t visible.

**Comment by SusanBrown** [comment]
But I see that the word "male" actually pasted into the issue. Sorry: time for bed.

**Comment by brundin** [comment]
SIB: It is 1:07 a.m, your time, after a "routine" demanding, exhausting day on your part.  Sleep!  (That was in the imperative.  :) ). -- MRB
-----Original Message-----

**Comment by brundin** [comment]
? 
-----Original Message-----
