### ISSUE TITLE
cwrc_entry.rng and orlando_biography.rng and orlando_writing.rng: revise TOPIC documentation

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#97]
There is confusion between the TOPIC and THEMETOPIC tags, with the description of the latter provided also for the former, in at least the first two of these and probably all three schemas.

The current documentation reads:
This element applies to both theme and topic. Theme is the central idea in a text stated either directly or indirectly; topic applies to interesting subjects appearing in a work that might not aspire to the status of a "theme" and is useful in genres such as educational or non-fictional texts.

It should be replaced by:
This element is designed to designate the name of a topic document or entry. For the topic or theme of a text, use TTHEMETOPIC.

**Comment by brundin** [comment]
Changed the documentation for the TTHEMETOPIC element in the cwrc_entry.rng, orlando_biography.rng, and orlando_writing.rng to read as follows: "This element is designed to designate the name of a topic document or entry. For the topic or theme of a text, use TTHEMETOPIC."
