### ISSUE TITLE
cwrc_entry.rng: add reg attribute to TTHEMETOPIC tag

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/CWRC-Schema#98]
The Playwrights project would like to have a standardized vocabulary for themes and topics in their materials, so could you please add a reg attribute?

**Comment by SusanBrown** [comment]
documentation for Reg attribute:
This attribute allows for the addition of an alternative or standardized label for a theme or topic if this is not sufficiently conveyed by contents of the tag.

**Comment by brundin** [comment]
Added a REG attribute to the element TTHEMETOPIC in the cwrc_entry.rng schema, with the following documentation statement: "This attribute allows for the addition of an alternative or standardized label for a theme or topic if this is not sufficiently conveyed by contents of the tag."
